import { Button } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app nn" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Welcome to Next.js! </div>
      <div>
      <Button variant="contained">Hello World</Button>
      </div>
    </div>
  );
};

export default Home;
